services:
  - type: web
    name: crypto-dashboard
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python dashboard.py
