name: Crypto Scanner – Tier 2 Auto

on:
  workflow_dispatch: {}
  schedule:
    # Run every 30 minutes (adjust as you like)
    - cron: "*/30 * * * *"

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      # Required API keys (already in your repo secrets)
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      COINMARKETCAL_API_KEY: ${{ secrets.COINMARKETCAL_API_KEY }}
      CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
      LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
      MESSARI_API_KEY: ${{ secrets.MESSARI_API_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      SANTIMENT_API_KEY: ${{ secrets.SANTIMENT_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      TAPPI_API_KEY: ${{ secrets.TAPPI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      # Scanner tuning (safe defaults)
      MAX_MARKETS_TO_SCAN: "200"      # how many markets to fetch from CMC
      MAX_TIER2_DEEP_CANDLES: "250"   # 5-min candles (~20 hours)
      EXCHANGE_STABLE: "USD"          # quote currency

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tier 2 auto-scan (no manual symbols)
        run: |
          python scanner_tier2.py
