name: Crypto Scanner Scheduler

on:
  schedule:
    - cron: "*/45 7-20 * * *"  # Every 45 minutes between 7:00 and 20:59 UTC
  workflow_dispatch:

jobs:
  tier1_and_tier2_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tier 1 Auto Scan and Extract Symbols
        id: tier1
        run: |
          echo "Calling Tier 1 /scan/auto endpoint..."
          response=$(curl -s -X GET https://crypto-trading-scanner.onrender.com/scan/auto)
          echo "Response: $response"
          echo "$response" > response.json
          # Extract symbols as comma-separated list
          symbols=$(jq -r '.results[].symbol' response.json | tr '\n' ',' | sed 's/,$//')
          echo "Extracted symbols: $symbols"
          echo "SYMBOLS=$symbols" >> $GITHUB_ENV

      - name: Trigger Tier 2 Manual Scan with Symbols
        if: env.SYMBOLS != ''
        run: |
          echo "Calling Tier 2 /scan/manual with symbols: $SYMBOLS"
          tier2_response=$(curl -s -X GET "https://crypto-trading-scanner.onrender.com/scan/manual?symbols=$SYMBOLS")
          echo "Tier 2 response: $tier2_response"
