name: Crypto Scanner Scheduler

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Call Render Deploy Hook (optional warm redeploy)
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -sSf -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" || true

      - name: Trigger Render Web Service Scan (scan_and_alert)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # Hit your service endpoints directly if publicly reachable:
          curl -sS "https://crypto-trading-scanner.onrender.com/scan/auto" >/dev/null || true
          curl -sS -X POST "https://crypto-trading-scanner.onrender.com/scan/alert" >/dev/null || true
