name: Crypto Scanner Scheduler

on:
  # Schedule: Every 45 minutes between 7:00 and 20:59 UTC
  schedule:
    - cron: "*/45 7-20 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  tier1_and_tier2:
    name: Tier 1 and Tier 2 Scan
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tier 1 Auto Scan and Save Symbols
        id: tier1
        run: |
          # Call the Tier 1 scan endpoint and save the response
          response=$(curl -s -X GET https://crypto-trading-scanner.onrender.com/scan/auto)
          echo "$response" > response.json
          # Extract symbols from the live scan results (expects .results[].symbol)
          symbols=$(cat response.json | jq -r '.results[].symbol' | tr '\n' ',' | sed 's/,$//')
          echo "SYMBOLS=$symbols" >> $GITHUB_ENV

      - name: Trigger Tier 2 Scan for Live Symbols
        if: env.SYMBOLS != ''
        run: |
          # Only trigger if there are symbols found by Tier 1 scan
          curl -X GET "https://crypto-trading-scanner.onrender.com/scan/manual?symbols=${{ env.SYMBOLS }}"
