name: Crypto Scanner Scheduler

# Run this workflow on a schedule and manually
on:
  schedule:
    # Every 10 minutes (can adjust)
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tier 1 Scanner
        run: |
          python scanner_tier1.py

      - name: Run Tier 2 Scanner (optional/manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          python scanner_tier2.py
