name: Keep Backend Alive

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -fsS --retry 3 https://your-render-backend-url/ || exit 1
